package jp.co.aforce.practice.Exception;

public class SomeClass {
//    public static void testMethod() throws AforceException1, AforceException2 {
//    	
//        try {
//            testMethod();
//        } catch (AforceException1 e) {
//            throw new AforceException2("AforceException2エラーが発生しました");
//        }
//        
//        try {
//            // 何らかの処理
//            throw new AforceException1("AforceException1エラーが発生しました");
//        } catch (AforceException1 e) {
//            throw e;
//        }
//        

    }
//}
